### ISSUE TITLE
rename this repo

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/forecast#23]
Rename this repo from stock-forecasting to only forecasting.
Now will contain more generic modules for make forecasting in general.

**Comment by nhomar** [comment]
- [ ] Reconfigure Travis links.
- [ ] Reconfigure coverage all.

@moylop260 I already changed the name of the repo can you help me with that.

**Comment by moylop260** [comment]
The name in this issue is: `forecasting`
The name in this repo is: `forecast`
What is the final name?

**Comment by moylop260** [comment]
- [x] Reconfigure travis-ci
- [x] Reconfigure coveralls.io
- [x] Change README bagdes url
