### ISSUE TITLE
Can not find web_widget_x2many_graph

### ISSUE THREAD

**Issue by alexalv** [Vauxoo/forecast#83]
Hello, I am trying to install forecasting modules, and I am unable to find web_widget_x2many_graph module which forecasting_smoothing_techniques module depends on. Can you provide me some information about where it can be located?

Tried to ask on odoo help forum first, no answer yet.

Thank you!

**Comment by nhomar** [comment]
In the Vauxoo/web repository.

On Friday, 10 June 2016, Aleksandr <notifications@github.com> wrote:

> Hello, I am trying to install forecasting modules, and I am unable to find
> web_widget_x2many_graph module which forecasting_smoothing_techniques
> module depends on. Can you provide me some information about where it can
> be located?
>
> Tried to ask on odoo help forum first, no answer yet.
>
> Thank you!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Vauxoo/forecast/issues/83>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAUqykZLM_nWEjtT4PvBU5eEVKi-Vzwxks5qKSt0gaJpZM4IyxAp>
> .
>


-- 
Sent from my mobile.

**Comment by zaoral** [comment]
Hi @alexalv 
You can find all the dependencies needed for forecast modules sinde [oca_dependencies.txt](https://github.com/Vauxoo/forecast/blob/8.0/oca_dependencies.txt) file in this repository

Best Regards

**Comment by alexalv** [comment]
Thank you!
